<?php

/**
 * @file
 * Contains drush_test.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drush_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drush_test module.
    case 'help.page.drush_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
