<?php

function location_schema() {
  $schema['location'] = array(
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'not null' => TRUE,
      ),
      'country' => array(
        'type' => 'varchar',
        'length' => 40,
        'not null' => TRUE,
      ),
      'state' => array(
        'type' => 'varchar',
        'length' => 40,
        'not null' => TRUE,
      ),
    ),
    'primary key' => array('id'),
  );

  return $schema;
}
