<?php

/**
 * @file
 * Contains custom_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_rest module.
    case 'help.page.custom_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Rest API module for demo') . '</p>';
      return $output;

    default:
  }
}
